"""Declarative Phase 5 skill manifests.

These definitions describe workflows only. They do not advertise a usable
runtime route: execution still requires the matching capability callbacks to
be registered with :class:`SkillExecutor`.
"""
from __future__ import annotations

from copy import deepcopy
from typing import Any


_BUILTINS: tuple[dict[str, Any], ...] = (
    {
        "schema_version": 1,
        "id": "chat.general",
        "name": "General chat",
        "version": "1.0.0",
        "description": "Generate a text response from a user prompt.",
        "inputs": [{"name": "prompt", "artifact": "text", "required": True}],
        "outputs": [{"name": "response", "artifact": "text", "required": True}],
        "requirements": {"capabilities": ["text.chat"]},
        "permissions": {"filesystem_read": "none", "filesystem_write": "none", "network": "none"},
        "policy": {"max_steps": 1, "timeout_seconds": 120},
        "ui": {"category": "Chat", "icon": "message-circle", "suggested_from": ["text/plain"]},
        "graph": [
            {"id": "reply", "type": "capability", "capability": "text.chat",
             "in": {"prompt": "$input.prompt"}, "accepts": {"prompt": "text"},
             "out": {"response": "text"}},
            {"id": "result", "type": "output", "in": {"response": "$reply.response"}},
        ],
    },
    {
        "schema_version": 1,
        "id": "image.describe",
        "name": "Describe image",
        "version": "1.0.0",
        "description": "Describe a user-provided image in text.",
        "inputs": [{"name": "image", "artifact": "image", "required": True}],
        "outputs": [{"name": "description", "artifact": "text", "required": True}],
        "requirements": {"capabilities": ["vision.understand"]},
        "permissions": {"filesystem_read": "none", "filesystem_write": "none", "network": "none"},
        "policy": {"max_steps": 1, "timeout_seconds": 120},
        "ui": {"category": "Images", "icon": "image", "suggested_from": ["image/*"]},
        "graph": [
            {"id": "describe", "type": "capability", "capability": "vision.understand",
             "in": {"image": "$input.image"}, "accepts": {"image": "image"},
             "out": {"description": "text"}},
            {"id": "result", "type": "output", "in": {"description": "$describe.description"}},
        ],
    },
    {
        "schema_version": 1,
        "id": "image.generate",
        "name": "Generate image",
        "version": "1.0.0",
        "description": "Generate an image from a prompt when a compatible local image-generation runtime and model are available.",
        "inputs": [{"name": "prompt", "artifact": "text", "required": True}],
        "outputs": [{"name": "image", "artifact": "image", "required": True}],
        "requirements": {"capabilities": ["image.generate"]},
        "permissions": {"filesystem_read": "none", "filesystem_write": "none", "network": "none"},
        "policy": {"max_steps": 1, "timeout_seconds": 300},
        "ui": {"category": "Images", "icon": "image-plus", "suggested_from": ["text/plain"]},
        "graph": [
            {"id": "generate", "type": "capability", "capability": "image.generate",
             "in": {"prompt": "$input.prompt"}, "accepts": {"prompt": "text"},
             "out": {"image": "image"}},
            {"id": "result", "type": "output", "in": {"image": "$generate.image"}},
        ],
    },
    {
        "schema_version": 1,
        "id": "image.edit-from-instruction",
        "name": "Edit image from instruction",
        "version": "1.0.0",
        "description": "Edit a user-provided image from an instruction when a compatible local image-editing runtime and model are available.",
        "inputs": [
            {"name": "image", "artifact": "image", "required": True},
            {"name": "instruction", "artifact": "text", "required": True},
        ],
        "outputs": [{"name": "image", "artifact": "image", "required": True}],
        "requirements": {"capabilities": ["image.edit"]},
        "permissions": {"filesystem_read": "user-selected-only", "filesystem_write": "none", "network": "none"},
        "policy": {"max_steps": 1, "timeout_seconds": 300},
        "ui": {"category": "Images", "icon": "image-edit", "suggested_from": ["image/*"]},
        "graph": [
            {"id": "edit", "type": "capability", "capability": "image.edit",
             "in": {"image": "$input.image", "instruction": "$input.instruction"},
             "accepts": {"image": "image", "instruction": "text"},
             "out": {"image": "image"}},
            {"id": "result", "type": "output", "in": {"image": "$edit.image"}},
        ],
    },
    {
        "schema_version": 1,
        "id": "document.summarize",
        "name": "Summarize document",
        "version": "1.0.0",
        "description": "Extract bounded document text and summarize it with a compatible local chat model.",
        "inputs": [{"name": "document", "artifact": "document", "required": True}],
        "outputs": [{"name": "summary", "artifact": "text", "required": True}],
        "requirements": {"capabilities": ["text.chat"]},
        "permissions": {"filesystem_read": "user-selected-only", "filesystem_write": "none", "network": "none"},
        "policy": {"max_steps": 2, "timeout_seconds": 180},
        "ui": {"category": "Documents", "icon": "file-text", "suggested_from": ["application/pdf", "text/markdown"]},
        "graph": [
            {"id": "prepare", "type": "tool", "tool_id": "document.summarize-prompt",
             "in": {"document": "$input.document"}, "accepts": {"document": "document"},
             "out": {"prompt": "text"}},
            {"id": "summarize", "type": "capability", "capability": "text.chat",
             "in": {"prompt": "$prepare.prompt"}, "accepts": {"prompt": "text"},
             "out": {"summary": "text"}},
            {"id": "result", "type": "output", "in": {"summary": "$summarize.summary"}},
        ],
    },
    {
        "schema_version": 1,
        "id": "document.answer-with-rag",
        "name": "Answer from document",
        "version": "1.0.0",
        "description": "Answer a question from one selected document using temporary lexical retrieval and explicit citations.",
        "inputs": [
            {"name": "document", "artifact": "document", "required": True},
            {"name": "question", "artifact": "text", "required": True},
        ],
        "outputs": [
            {"name": "answer", "artifact": "text", "required": True},
            {"name": "citations", "artifact": "json", "required": True},
        ],
        "requirements": {"capabilities": ["text.chat"]},
        "permissions": {"filesystem_read": "user-selected-only", "filesystem_write": "none", "network": "none"},
        "policy": {"max_steps": 2, "timeout_seconds": 180},
        "ui": {"category": "Documents", "icon": "search", "suggested_from": ["application/pdf", "text/markdown", "text/plain"]},
        "graph": [
            {"id": "retrieve", "type": "tool", "tool_id": "document.retrieve-temporary",
             "in": {"document": "$input.document", "question": "$input.question"},
             "accepts": {"document": "document", "question": "text"},
             "out": {"prompt": "text", "context": "text", "citations": "json"}},
            {"id": "answer", "type": "capability", "capability": "text.chat",
             "in": {"prompt": "$retrieve.prompt"}, "accepts": {"prompt": "text"},
             "out": {"response": "text"}},
            {"id": "result", "type": "output", "in": {
                "answer": "$answer.response", "citations": "$retrieve.citations",
            }},
        ],
    },
    {
        "schema_version": 1,
        "id": "document.extract-text",
        "name": "Extract document text",
        "version": "1.0.0",
        "description": "Extract bounded text from a selected TXT, Markdown, or text-based PDF without loading a model.",
        "inputs": [{"name": "document", "artifact": "document", "required": True}],
        "outputs": [{"name": "text", "artifact": "text", "required": True}],
        "requirements": {"capabilities": []},
        "permissions": {"filesystem_read": "user-selected-only", "filesystem_write": "none", "network": "none"},
        "policy": {"max_steps": 1, "timeout_seconds": 60},
        "ui": {"category": "Documents", "icon": "file-text", "suggested_from": ["text/plain", "text/markdown", "application/pdf"]},
        "graph": [
            {"id": "extract", "type": "tool", "tool_id": "document.extract-text",
             "in": {"document": "$input.document"}, "accepts": {"document": "document"},
             "out": {"text": "text"}},
            {"id": "result", "type": "output", "in": {"text": "$extract.text"}},
        ],
    },
    {
        "schema_version": 1,
        "id": "voice.transcribe",
        "name": "Transcribe audio",
        "version": "1.0.0",
        "description": "Transcribe user-provided audio into text. Review and edit this transcript before sending it to voice.respond.",
        "inputs": [{"name": "audio", "artifact": "audio", "required": True}],
        "outputs": [{"name": "transcript", "artifact": "text", "required": True}],
        "requirements": {"capabilities": ["audio.transcribe"]},
        "permissions": {"microphone": "none", "filesystem_read": "user-selected-only", "network": "none"},
        "policy": {"max_steps": 1, "timeout_seconds": 180},
        "ui": {"category": "Audio", "icon": "audio-lines", "suggested_from": ["audio/*"]},
        "graph": [
            {"id": "transcribe", "type": "tool", "tool_id": "audio.transcribe",
             "in": {"audio": "$input.audio"}, "accepts": {"audio": "audio"},
             "out": {"transcript": "text"}},
            {"id": "result", "type": "output", "in": {"transcript": "$transcribe.transcript"}},
        ],
    },
    {
        "schema_version": 1,
        "id": "voice.conversation",
        "name": "Voice conversation",
        "version": "1.0.0",
        "description": "Transcribe audio, generate a text reply, and synthesize spoken audio when compatible routes are available.",
        "inputs": [{"name": "audio", "artifact": "audio", "required": True}],
        "outputs": [
            {"name": "response", "artifact": "text", "required": True},
            {"name": "reply_audio", "artifact": "audio", "required": True},
        ],
        "requirements": {"capabilities": ["audio.transcribe", "text.chat", "audio.synthesize"]},
        "permissions": {"microphone": "none", "filesystem_read": "user-selected-only", "filesystem_write": "none", "network": "none"},
        "policy": {"max_steps": 3, "timeout_seconds": 300},
        "ui": {"category": "Audio", "icon": "audio-lines", "suggested_from": ["audio/*"]},
        "graph": [
            {"id": "transcribe", "type": "tool", "tool_id": "audio.transcribe",
             "in": {"audio": "$input.audio"}, "accepts": {"audio": "audio"},
             "out": {"transcript": "text"}},
            {"id": "reply", "type": "capability", "capability": "text.chat",
             "in": {"prompt": "$transcribe.transcript"}, "accepts": {"prompt": "text"},
             "out": {"response": "text"}},
            {"id": "speak", "type": "tool", "tool_id": "audio.synthesize",
             "in": {"text": "$reply.response"}, "accepts": {"text": "text"},
             "out": {"audio": "audio"}},
            {"id": "result", "type": "output", "in": {
                "response": "$reply.response", "reply_audio": "$speak.audio",
            }},
        ],
    },
    {
        "schema_version": 1,
        "id": "voice.respond",
        "name": "Respond to reviewed transcript",
        "version": "1.0.0",
        "description": "Generate a local text reply and spoken audio from an explicitly supplied, user-reviewed transcript. It does not transcribe or auto-submit audio.",
        "inputs": [{"name": "transcript", "artifact": "text", "required": True}],
        "outputs": [
            {"name": "response", "artifact": "text", "required": True},
            {"name": "reply_audio", "artifact": "audio", "required": True},
        ],
        "requirements": {"capabilities": ["text.chat", "audio.synthesize"]},
        "permissions": {"microphone": "none", "filesystem_read": "none", "filesystem_write": "none", "network": "none"},
        "policy": {"max_steps": 2, "timeout_seconds": 180},
        "ui": {"category": "Audio", "icon": "audio-lines", "suggested_from": ["text/plain"]},
        "graph": [
            {"id": "reply", "type": "capability", "capability": "text.chat",
             "in": {"prompt": "$input.transcript"}, "accepts": {"prompt": "text"},
             "out": {"response": "text"}},
            {"id": "speak", "type": "tool", "tool_id": "audio.synthesize",
             "in": {"text": "$reply.response"}, "accepts": {"text": "text"},
             "out": {"audio": "audio"}},
            {"id": "result", "type": "output", "in": {
                "response": "$reply.response", "reply_audio": "$speak.audio",
            }},
        ],
    },
    {
        "schema_version": 1,
        "id": "document.create-html",
        "name": "Create HTML document",
        "version": "1.0.0",
        "description": "Render plain text into a safe, self-contained HTML document.",
        "inputs": [{"name": "text", "artifact": "text", "required": True}],
        "outputs": [{"name": "document", "artifact": "document", "required": True}],
        "requirements": {"capabilities": []},
        "permissions": {"filesystem_read": "none", "filesystem_write": "none", "network": "none"},
        "policy": {"max_steps": 1, "timeout_seconds": 30},
        "ui": {"category": "Documents", "icon": "file-code", "suggested_from": ["text/plain", "text/markdown"]},
        "graph": [
            {"id": "render", "type": "tool", "tool_id": "document.render-html",
             "in": {"text": "$input.text"}, "accepts": {"text": "text"}, "out": {"document": "document"}},
            {"id": "result", "type": "output", "in": {"document": "$render.document"}},
        ],
    },
    {
        "schema_version": 1,
        "id": "document.create-pdf",
        "name": "Create PDF document",
        "version": "1.0.0",
        "description": "Render plain text into a paginated PDF document.",
        "inputs": [{"name": "text", "artifact": "text", "required": True}],
        "outputs": [{"name": "document", "artifact": "document", "required": True}],
        "requirements": {"capabilities": []},
        "permissions": {"filesystem_read": "none", "filesystem_write": "none", "network": "none"},
        "policy": {"max_steps": 1, "timeout_seconds": 30},
        "ui": {"category": "Documents", "icon": "file-text", "suggested_from": ["text/plain", "text/markdown"]},
        "graph": [
            {"id": "render", "type": "tool", "tool_id": "document.render-pdf",
             "in": {"text": "$input.text"}, "accepts": {"text": "text"}, "out": {"document": "document"}},
            {"id": "result", "type": "output", "in": {"document": "$render.document"}},
        ],
    },
    {
        "schema_version": 1,
        "id": "document.create-report",
        "name": "Create structured report",
        "version": "1.0.0",
        "description": "Render a structured report object as a safe HTML document.",
        "inputs": [{"name": "report", "artifact": "json", "required": True}],
        "outputs": [{"name": "document", "artifact": "document", "required": True}],
        "requirements": {"capabilities": []},
        "permissions": {"filesystem_read": "none", "filesystem_write": "none", "network": "none"},
        "policy": {"max_steps": 1, "timeout_seconds": 30},
        "ui": {"category": "Documents", "icon": "file-text", "suggested_from": ["application/json"]},
        "graph": [
            {"id": "render", "type": "tool", "tool_id": "document.render-report",
             "in": {"report": "$input.report"}, "accepts": {"report": "json"}, "out": {"document": "document"}},
            {"id": "result", "type": "output", "in": {"document": "$render.document"}},
        ],
    },
    {
        "schema_version": 1,
        "id": "document.create-report-pdf",
        "name": "Create report PDF",
        "version": "1.0.0",
        "description": "Render a bounded structured report as a paginated PDF.",
        "inputs": [{"name": "report", "artifact": "json", "required": True}],
        "outputs": [{"name": "document", "artifact": "document", "required": True}],
        "requirements": {"capabilities": []},
        "permissions": {"filesystem_read": "none", "filesystem_write": "none", "network": "none"},
        "policy": {"max_steps": 1, "timeout_seconds": 30},
        "ui": {"category": "Documents", "icon": "file-pdf", "suggested_from": ["application/json"]},
        "graph": [
            {"id": "render", "type": "tool", "tool_id": "document.render-report-pdf",
             "in": {"report": "$input.report"}, "accepts": {"report": "json"}, "out": {"document": "document"}},
            {"id": "result", "type": "output", "in": {"document": "$render.document"}},
        ],
    },
)


def builtin_skill_manifests() -> tuple[dict[str, Any], ...]:
    """Return detached manifests for the initial built-in skills.

    Capability-backed definitions require real registered runtime routes;
    document extraction uses only a bounded local parser. No live route
    availability is inferred by this module.
    """
    return tuple(deepcopy(item) for item in _BUILTINS)


__all__ = ["builtin_skill_manifests"]
