import { ChangeDetectionStrategy, Component, OnInit, signal } from '@angular/core';
import { ApiService } from '../core/api.service';

type AgentAudit = { name: string; status: string; result_snippet: string; duration_ms: number; argument_names: string[] };
type Message = { role: string; content: string; created_at?: string };

@Component({
  selector: 'ai-agent-page', standalone: true, changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="page-head"><div><div class="eyebrow">WORKSPACE</div><h1>Agent</h1><p>Ask AI Dream to inspect local hardware, installed models, and runtime status.</p></div><span class="page-badge"><i></i>READ ONLY</span></div>
    @if (error()) { <div class="error" role="alert">{{ error() }} <button (click)="error.set('')">Dismiss</button></div> }
    <div class="agent-layout">
      <aside class="surface sessions"><div class="session-head"><b>Conversations</b><button (click)="createChat()" [disabled]="busy()">＋ New</button></div>
        @for (chat of chats(); track chat.id) { <button class="session" [disabled]="busy()" [class.selected]="chat.id === chatId()" (click)="selectChat(chat.id)">{{ chat.title || 'New chat' }}</button> }
        @if (!chats().length) { <p class="muted">No agent conversations yet.</p> }
      </aside>
      <section class="surface work"><div class="model-row"><label for="agent-model">Local model</label><select id="agent-model" [value]="modelId()" (change)="modelId.set($any($event.target).value)" [disabled]="busy()"><option value="">Select a model</option>@for (model of models(); track model.id) { <option [value]="model.id">{{ model.name || model.id }}</option> }</select><button (click)="reload()" [disabled]="busy()">↻</button></div>
        <div class="scope-note"><b>Allowed tools</b><span>Hardware status</span><span>Local model list and metadata</span><span>Runtime status</span><small>No shell, filesystem writes, installs, or downloads.</small></div>
        <div class="transcript" aria-live="polite">
          @for (message of messages(); track $index) { <article class="message" [class.user]="message.role === 'user'"><b>{{ message.role === 'user' ? 'You' : 'AI Dream' }}</b><p>{{ message.content }}</p></article> }
          @if (busy()) { <div class="working" role="status">{{ status() || 'Agent is checking local information…' }}</div> }
          @if (audit().length) { <section class="audit"><header><b>Tool audit</b><span>{{ stopReason() }}</span></header>@for (item of audit(); track $index) { <div class="audit-row"><strong>{{ item.name }}</strong><span>{{ item.status }} · {{ item.duration_ms }} ms</span><p>{{ item.result_snippet }}</p></div> }</section> }
        </div>
        <div class="composer"><textarea rows="3" placeholder="Ask about this device, your models, or runtime…" [value]="prompt()" (input)="prompt.set($any($event.target).value)" (keydown)="onKey($event)" [disabled]="busy()"></textarea>
          @if (busy()) { <button class="stop" (click)="cancel()">Stop agent</button> } @else { <button (click)="run()" [disabled]="!api.connected() || !chatId() || !modelId() || !prompt().trim()">Run agent <span>↗</span></button> }
        </div><p class="footnote">Tool calls are limited to 4 per turn, with a 45 second time limit. The bounded audit is saved with the conversation.</p>
      </section>
    </div>
  `,
  styles: [`
    :host{display:block}.agent-layout{display:grid;grid-template-columns:minmax(190px,240px) 1fr;gap:16px;min-height:60vh}.surface{background:#1c1d21;border:1px solid #303137;border-radius:10px}.sessions{padding:12px;height:max-content}.session-head,.model-row{display:flex;align-items:center;gap:10px}.session-head{justify-content:space-between;padding-bottom:12px;border-bottom:1px solid #303137}.session-head button,.model-row button{border:0;border-radius:7px;background:#303137;color:#e5e7eb;padding:7px 10px;cursor:pointer}.session{display:block;width:100%;text-align:left;padding:10px;margin-top:7px;background:transparent;color:#c7c8cd;border:0;border-radius:6px;cursor:pointer;overflow:hidden;text-overflow:ellipsis}.session.selected{background:#303137;color:white}.muted,.footnote{color:#93959d;font-size:12px}.work{display:flex;flex-direction:column;min-height:60vh;padding:14px}.model-row label{font-size:13px;color:#aeb0b7}.model-row select{flex:1;min-width:0;background:#292a2f;color:white;border:1px solid #414249;border-radius:6px;padding:8px}.scope-note{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0;padding:10px;border:1px solid #37383e;border-radius:7px;color:#c8cad0;font-size:12px}.scope-note b{color:white}.scope-note span{background:#292a30;border-radius:12px;padding:3px 8px}.scope-note small{width:100%;color:#92949b}.transcript{flex:1;overflow:auto;max-height:48vh;padding:4px 0}.message{max-width:850px;margin:12px auto;padding:12px 14px;background:#25262b;border-radius:9px;color:#e6e7eb}.message.user{background:#262a34}.message b{font-size:12px;color:#aab2c5}.message p,.audit-row p{white-space:pre-wrap;overflow-wrap:anywhere;margin:6px 0 0;line-height:1.5}.working{padding:12px;color:#9da6ba}.audit{max-width:850px;margin:14px auto;padding:12px;border:1px solid #3a3c43;border-radius:9px}.audit header{display:flex;justify-content:space-between;color:#bec3cf}.audit header span{font-size:12px;color:#a0a3aa}.audit-row{padding:9px 0;border-top:1px solid #33353b;margin-top:8px}.audit-row strong{font-size:12px}.audit-row span{float:right;color:#a4a6ae;font-size:11px}.audit-row p{font-size:12px;color:#b8bac1}.composer{display:flex;gap:10px;align-items:end;padding-top:12px;border-top:1px solid #303137}.composer textarea{flex:1;resize:vertical;min-width:0;background:#25262b;color:white;border:1px solid #414249;border-radius:8px;padding:11px;font:inherit}.composer button{border:0;border-radius:7px;background:#3584f6;color:white;padding:11px 15px;cursor:pointer}.composer button:disabled,.session-head button:disabled{opacity:.5;cursor:not-allowed}.composer .stop{background:#60383a}.footnote{margin:9px 0 0}.error{padding:10px;background:#492f32;color:#ffd6da;border-radius:7px;margin-bottom:12px}.error button{float:right}@media(max-width:760px){.agent-layout{grid-template-columns:1fr}.sessions{max-height:170px;overflow:auto}.work{min-height:55vh}}
  `]
})
export class AgentPage implements OnInit {
  readonly chats = signal<any[]>([]); readonly models = signal<any[]>([]); readonly messages = signal<Message[]>([]);
  readonly chatId = signal(''); readonly modelId = signal(''); readonly prompt = signal(''); readonly busy = signal(false);
  readonly status = signal(''); readonly error = signal(''); readonly answer = signal(''); readonly audit = signal<AgentAudit[]>([]); readonly stopReason = signal('');
  private aborter: AbortController | null = null;
  constructor(readonly api: ApiService) {}
  ngOnInit() { void this.initialize(); }
  async initialize() { await this.api.check(); if (!this.api.connected()) { this.error.set(this.api.error() || 'Local API is unavailable.'); return; } this.reload(); }
  reload() { this.api.get<any>('/api/models').subscribe({ next: r => { this.models.set(r?.data?.models || []); if (!this.modelId() && this.models().length) this.modelId.set(this.models()[0].id); }, error: e => this.error.set(e?.error?.error || 'Could not load models.') }); this.api.get<any>('/api/chats').subscribe({ next: r => { this.chats.set(r?.data?.chats || []); if (!this.chatId() && this.chats().length) this.selectChat(this.chats()[0].id); }, error: e => this.error.set(e?.error?.error || 'Could not load conversations.') }); }
  createChat() { if (this.busy()) return; this.api.post<any>('/api/chats', { title: 'Agent session' }).subscribe({ next: r => { const chat = r?.data?.chat; if (chat?.id) { this.chats.update(items => [chat, ...items]); this.selectChat(chat.id); } }, error: e => this.error.set(e?.error?.error || 'Could not create a conversation.') }); }
  selectChat(id: string) { if (this.busy()) return; this.chatId.set(id); this.messages.set([]); this.audit.set([]); this.stopReason.set(''); if (!id) return; this.api.get<any>(`/api/chats/${encodeURIComponent(id)}`).subscribe({ next: r => { const chat = r?.data?.chat; if (chat?.id === id && this.chatId() === id) { this.messages.set(chat.messages || []); const latest = chat.agent_audits?.at(-1); this.audit.set(latest?.tools || []); this.stopReason.set(latest ? `${latest.stop_reason || 'completed'} · ${latest.tool_call_count || 0} tool calls` : ''); } }, error: e => this.error.set(e?.error?.error || 'Could not load conversation.') }); }
  onKey(event: KeyboardEvent) { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void this.run(); } }
  async run() { const text = this.prompt().trim(), chatId = this.chatId(), modelId = this.modelId(); if (!text || !chatId || !modelId || this.busy()) return; const old = this.messages(); this.prompt.set(''); this.error.set(''); this.answer.set(''); this.audit.set([]); this.stopReason.set(''); this.messages.update(items => [...items, { role: 'user', content: text }]); this.busy.set(true); this.status.set('Starting bounded read-only agent…'); this.aborter = new AbortController();
    try { const res = await fetch(`${this.api.baseUrl()}/api/agent`, { method: 'POST', headers: { 'Content-Type': 'application/json', Accept: 'text/event-stream' }, body: JSON.stringify({ chat_id: chatId, model_id: modelId, prompt: text }), signal: this.aborter.signal }); if (!res.ok) throw new Error(await res.text()); if (!res.body) throw new Error('Agent stream unavailable.'); await this.readEvents(res.body); if (!this.answer()) throw new Error('Agent ended without a response.'); this.messages.update(items => [...items, { role: 'assistant', content: this.answer() }]); }
    catch (e) { const canceled = e instanceof DOMException && e.name === 'AbortError'; if (!canceled) this.error.set(e instanceof Error ? e.message : 'Agent request failed.'); if (this.chatId() === chatId) this.messages.set(old); if (canceled) this.status.set('Agent stopped. Incomplete turn discarded.'); }
    finally { this.busy.set(false); this.aborter = null; if (this.status() !== 'Agent stopped. Incomplete turn discarded.') this.status.set(''); }
  }
  cancel() { this.aborter?.abort(); }
  private async readEvents(body: ReadableStream<Uint8Array>) { const reader = body.getReader(), decoder = new TextDecoder(); let buffer = ''; try { while (true) { const { value, done } = await reader.read(); buffer += decoder.decode(value, { stream: !done }); let match: RegExpExecArray | null; while ((match = /\r?\n\r?\n/.exec(buffer))) { const frame = buffer.slice(0, match.index); buffer = buffer.slice(match.index + match[0].length); await this.handleFrame(frame); } if (done) break; } if (buffer.trim()) await this.handleFrame(buffer); } finally { reader.releaseLock(); } }
  private async handleFrame(frame: string) { let name = 'message'; const data: string[] = []; for (const line of frame.split(/\r?\n/)) { if (line.startsWith('event:')) name = line.slice(6).trim(); else if (line.startsWith('data:')) data.push(line.slice(5).trimStart()); } if (!data.length) return; const payload = JSON.parse(data.join('\n')); if (name === 'status') { this.status.set(payload.message || 'Agent is working…'); return; } if (name === 'error' || payload.error) throw new Error(payload.error || 'Agent failed.'); if (name === 'complete') { this.answer.set(typeof payload.assistant === 'string' ? payload.assistant : ''); this.audit.set(payload.agent?.tools || []); this.stopReason.set(`${payload.agent?.stop_reason || 'completed'} · ${payload.agent?.tool_call_count || 0} tool calls`); } }
}
