import { ChangeDetectionStrategy, Component, OnInit, signal } from '@angular/core';
import { JsonPipe } from '@angular/common';
import { ApiService } from '../core/api.service';
type Model = {id:string; path?:string; name?:string};
type Backend = {name:string; available:boolean; capabilities:Record<string,any>};
@Component({standalone:true,imports:[JsonPipe],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<div class="page-head"><div><div class="eyebrow">SYSTEM</div><h1>Runtime</h1><p>Choose and load a model without sending a chat message.</p></div></div>
@if (!api.connected()) {<div class="chat-notice error-notice"><b>Local API unavailable</b><p>Start AI Dream, then retry.</p><button (click)="initialize()">Retry</button></div>}
<section class="surface" style="padding:20px;display:grid;gap:16px"><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px">
<label>Model<select [value]="modelId()" (change)="modelId.set($any($event.target).value)"><option value="">Select a model</option>@for(m of models();track m.id){<option [value]="m.id">{{m.name||m.path||m.id}}</option>}</select></label>
<label>Backend<select [value]="backendName()" (change)="backendName.set($any($event.target).value)">@for(b of backends();track b.name){<option [value]="b.name" [disabled]="!b.available">{{b.name}}</option>}</select></label>
@if(supports('device_selection')){<label>GPU / device<select [value]="device()" (change)="device.set($any($event.target).value)"><option value="">Runtime default</option>@for(d of devices();track d.runtime_id||d.id||d.name){<option [value]="d.runtime_id||d.id||d.name">{{d.name||d.runtime_id||d.id}}</option>}</select></label>}</div>
<details><summary>Advanced settings</summary><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;padding-top:12px">
@for(f of numericFields;track f.key){@if(supports(f.cap)){<label>{{f.label}}<input type="number" min="0" [value]="values()[f.key]??''" (input)="setValue(f.key,$any($event.target).value)"></label>}}
@if(supports('split_mode')){<label>Split mode<input [value]="values()['split_mode']||''" (input)="setValue('split_mode',$any($event.target).value)"></label>}
@if(supports('tensor_split')){<label>Tensor split<input [value]="values()['tensor_split']||''" placeholder="1,1" (input)="setValue('tensor_split',$any($event.target).value)"></label>}
@if(supports('main_gpu')){<label>Main GPU<input type="number" min="0" [value]="values()['main_gpu']??''" (input)="setValue('main_gpu',$any($event.target).value)"></label>}
@for(f of booleanFields;track f.key){@if(supports(f.cap)){<label style="display:flex;align-items:center;gap:8px"><input type="checkbox" [checked]="values()[f.key]||false" (change)="setValue(f.key,$any($event.target).checked)">{{f.label}}</label>}}
@if(supports('device_selection')){<label style="display:flex;align-items:center;gap:8px"><input type="checkbox" [checked]="manualDevice()" (change)="manualDevice.set($any($event.target).checked)">Manual device override</label>@if(manualDevice()){<label>Runtime device identifier<input [value]="device()" placeholder="ROCm0, Vulkan1…" (input)="device.set($any($event.target).value)"></label>}}</div></details>
<div style="display:flex;gap:8px;flex-wrap:wrap"><button class="send-button" (click)="load()" [disabled]="busy()||!modelId()||!api.connected()">Load model</button><button class="secondary-button" (click)="unload()" [disabled]="busy()||!api.connected()">Unload model</button><button class="secondary-button" (click)="load()" [disabled]="busy()||!modelId()||!api.connected()">Reload model</button><button class="secondary-button" (click)="refreshStatus()">Runtime status</button><button class="secondary-button" (click)="showCommand()" [disabled]="!modelId()">Show effective llama.cpp command</button></div>
@if(status()){<pre>{{status()|json}}</pre>}@if(notice()){<p role="status">{{notice()}}</p>}@if(error()){<p class="error-line" role="alert">{{error()}}</p>}
@if(command()){<div><label>Effective command<textarea readonly rows="3" [value]="command()"></textarea></label><button class="secondary-button" (click)="copyCommand()">{{copied()?'Copied':'Copy command'}}</button></div>}
</section>`})
export class RuntimePage implements OnInit {
readonly models=signal<Model[]>([]);readonly backends=signal<Backend[]>([]);readonly devices=signal<any[]>([]);readonly modelId=signal('');readonly backendName=signal('llama.cpp');readonly device=signal('');readonly manualDevice=signal(false);readonly values=signal<Record<string,any>>({});readonly status=signal<any>(null);readonly busy=signal(false);readonly notice=signal('');readonly error=signal('');readonly command=signal('');readonly copied=signal(false);
readonly numericFields=[{key:'gpu_layers',label:'GPU layers',cap:'gpu_layers'},{key:'context_size',label:'Context size',cap:'context_size'},{key:'threads',label:'Threads',cap:'threads'},{key:'batch_size',label:'Batch size',cap:'batch_size'},{key:'physical_batch_size',label:'Physical batch size',cap:'physical_batch_size'},{key:'max_concurrent',label:'Max concurrent',cap:'max_concurrent'}];
readonly booleanFields=[{key:'flash_attention',label:'Flash attention',cap:'flash_attention'},{key:'unified_kv_cache',label:'Unified KV cache',cap:'unified_kv_cache'},{key:'offload_kv_cache',label:'Offload KV cache',cap:'offload_kv_cache'},{key:'mmap',label:'Memory map',cap:'mmap'},{key:'keep_model_in_memory',label:'Keep model in memory',cap:'keep_model_in_memory'},{key:'fit',label:'Fit to available memory',cap:'fit'}];
constructor(readonly api:ApiService){} ngOnInit(){void this.initialize();}
async initialize(){await this.api.check();if(!this.api.connected())return;try{const [m,r,h]=await Promise.all([this.api.request<any>('/api/models'),this.api.request<any>('/api/runtime'),this.api.request<any>('/api/hardware')]);const md=unwrap(m),rd=unwrap(r),hd=unwrap(h);this.models.set(md.models||md);this.backends.set(rd.backends||[]);this.devices.set(rd.devices||hd.hardware?.gpus||[]);this.status.set(rd.status||null);if(!this.backends().some(x=>x.name===this.backendName()))this.backendName.set(this.backends()[0]?.name||'');}catch(e){this.error.set(message(e));}}
private get backend(){return this.backends().find(b=>b.name===this.backendName());} supports(k:string){return Boolean(this.backend?.capabilities?.[k]);}setValue(k:string,v:any){const integerKeys=['gpu_layers','context_size','threads','batch_size','physical_batch_size','max_concurrent','main_gpu'];const normalized=integerKeys.includes(k)&&v!==''?Number(v):v;this.values.update(x=>({...x,[k]:normalized}));}
private payload(){const load:any={...this.values()},placement:any={};for(const k of ['gpu_layers','device','split_mode','tensor_split','main_gpu'])if(load[k]!==undefined&&load[k]!==''){placement[k]=load[k];delete load[k];}if(this.device())placement.device=this.device();return{model_id:this.modelId(),backend:this.backendName(),placement,load};}
async load(){this.busy.set(true);this.error.set('');this.notice.set('Loading model…');this.command.set('');try{this.status.set(unwrap(await this.api.request('/api/runtime/load',this.payload())));this.notice.set('Model loaded.');await this.refreshStatus();}catch(e){this.notice.set('');this.error.set(message(e));}finally{this.busy.set(false);}}
async unload(){this.busy.set(true);this.error.set('');try{this.status.set(unwrap(await this.api.request('/api/runtime/unload',{})));this.notice.set('Model unloaded.');}catch(e){this.error.set(message(e));}finally{this.busy.set(false);}}
async refreshStatus(){try{this.status.set(unwrap(await this.api.request('/api/runtime/status')));}catch(e){this.error.set(message(e));}}
async showCommand(){try{const r=unwrap(await this.api.request<any>('/api/runtime/command',this.payload()));this.command.set(String(r.command||''));}catch(e){this.error.set(message(e));}}
copyCommand(){void navigator.clipboard?.writeText(this.command());this.copied.set(true);}}
function unwrap(v:any):any{return v?.data??v;}function message(e:any):string{return e?.error?.message||e?.message||String(e);}
