import { ChangeDetectionStrategy, Component, OnInit, signal } from '@angular/core';
import { ApiService } from '../core/api.service';
import { GlobalSettings, SettingsService } from '../core/settings.service';
import { RuntimeLoadOptions, RuntimePlacement } from '../core/control-plane.types';

@Component({standalone:true,changeDetection:ChangeDetectionStrategy.OnPush,template:`
<div class="page-head"><div><div class="eyebrow">PREFERENCES</div><h1>Settings</h1><p>Set local defaults used when resolving model runtime configuration.</p></div><span class="page-badge"><i></i>LOCAL</span></div>
<section class="surface settings-card"><div class="section-title"><div><h2>Local API</h2><p>Requests stay on your machine.</p></div><span class="status-tag" [class.ok]="api.connected()">{{ api.connected() ? 'Connected' : api.connection() === 'checking' ? 'Checking' : 'Unavailable' }}</span></div><label class="field-label" for="api-url">Base URL</label><div class="input-row"><input id="api-url" type="url" [value]="url" (input)="url = $any($event.target).value" spellcheck="false" placeholder="http://127.0.0.1:8765" (keydown.enter)="saveApiUrl()"><button class="primary-button" (click)="saveApiUrl()">Save & check</button></div><p class="help">Health check: <code>GET {{ api.baseUrl() }}/api/health</code>. The base URL is stored in this browser's local storage.</p>@if (urlError()) {<p class="error-line" role="alert">{{urlError()}}</p>} @else if (api.error()) {<p class="error-line">{{ api.error() }}</p>}</section>
@if(loading()){<p role="status">Loading settings…</p>}
@if(loadError()){<section class="surface settings-card"><p class="error-line" role="alert">{{loadError()}}</p><button class="secondary-button" (click)="initialize()">Retry settings</button></section>}
@if(settings(); as s){<section class="surface settings-card"><div class="section-title"><div><h2>Runtime defaults</h2><p>Applied before model profile, chat, and request overrides.</p></div></div>
<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;margin:12px 0"><label>Default backend<input [value]="s.runtime_defaults.backend_name||''" (input)="updateBackend($any($event.target).value)" placeholder="Runtime default"></label><label>Default runtime id<input [value]="s.runtime_defaults.runtime_id||''" (input)="updateRuntime($any($event.target).value)" placeholder="Runtime default"></label></div>
<h3>Default placement</h3><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;margin:12px 0"><label>GPU layers<input type="number" [value]="s.runtime_defaults.placement.gpu_layers??''" (input)="updatePlacement('gpu_layers',$any($event.target).value)"></label><label>Device<input [value]="s.runtime_defaults.placement.device||''" (input)="updatePlacement('device',$any($event.target).value)" placeholder="Runtime default"></label><label>Split mode<input [value]="s.runtime_defaults.placement.split_mode||''" (input)="updatePlacement('split_mode',$any($event.target).value)"></label><label>Tensor split<input [value]="s.runtime_defaults.placement.tensor_split||''" (input)="updatePlacement('tensor_split',$any($event.target).value)"></label><label>Main GPU<input type="number" [value]="s.runtime_defaults.placement.main_gpu??''" (input)="updatePlacement('main_gpu',$any($event.target).value)"></label></div>
<h3>Default load settings</h3><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;margin:12px 0">@for(field of numberFields;track field.key){<label>{{field.label}}<input type="number" [value]="s.runtime_defaults.load[field.key]??''" (input)="updateLoadNumber(field.key,$any($event.target).value)"></label>}</div>
<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;margin:12px 0">@for(field of boolFields;track field.key){<label class="check-setting"><input type="checkbox" [checked]="s.runtime_defaults.load[field.key]??false" (change)="updateLoadBool(field.key,$any($event.target).checked)">{{field.label}}</label>}<label>NUMA<input [value]="s.runtime_defaults.load.numa||''" (input)="updateLoadString('numa',$any($event.target).value)"></label><label>KV cache type K<input [value]="s.runtime_defaults.load.kv_cache_type_k||''" (input)="updateLoadString('kv_cache_type_k',$any($event.target).value)"></label><label>KV cache type V<input [value]="s.runtime_defaults.load.kv_cache_type_v||''" (input)="updateLoadString('kv_cache_type_v',$any($event.target).value)"></label></div>
<h3>Profile resolution</h3><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;margin:12px 0"><label>Default profile behavior<select [value]="s.default_profile_behavior" (change)="updateBehavior($any($event.target).value)"><option value="model">Model profile</option><option value="global">Global defaults</option></select></label><label class="check-setting"><input type="checkbox" [checked]="s.keep_last_model_loaded" (change)="updateKeepLoaded($any($event.target).checked)">Keep last model loaded</label></div>
<div style="display:flex;gap:8px;align-items:center"><button class="primary-button" (click)="saveSettings()" [disabled]="saving()">{{saving()?'Saving…':'Save settings'}}</button>@if(saved()){<span role="status">Saved</span>}</div>@if(saveError()){<p class="error-line" role="alert">{{saveError()}}</p>}</section>
<section class="surface settings-card"><h2>Local paths</h2><p class="help">Diagnostics only. Paths are read-only and no filesystem browsing or arbitrary path access is available.</p><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;margin:12px 0"><label>Managed models directory<input readonly [value]="s.managed_models_dir"></label><label>Configuration directory<input readonly [value]="s.config_dir"></label><label>Data directory<input readonly [value]="s.data_dir"></label></div></section>}
`})
export class SettingsPage implements OnInit {
  url=this.api.baseUrl(); readonly urlError=signal(''); readonly loading=signal(false); readonly saving=signal(false); readonly saved=signal(false);
  readonly loadError=signal(''); readonly saveError=signal(''); readonly settings=signal<GlobalSettings|null>(null);
  readonly numberFields: {key: 'context_size'|'threads'|'batch_size'|'physical_batch_size'|'max_concurrent'|'threads_batch';label:string}[]=[
    {key:'context_size',label:'Context size'},{key:'threads',label:'Threads'},{key:'batch_size',label:'Batch size'},
    {key:'physical_batch_size',label:'Physical batch size'},{key:'max_concurrent',label:'Max concurrent'},{key:'threads_batch',label:'Batch threads'}];
  readonly boolFields: {key: 'continuous_batching'|'mlock'|'flash_attention'|'unified_kv_cache'|'offload_kv_cache'|'mmap'|'keep_model_in_memory'|'fit';label:string}[]=[
    {key:'continuous_batching',label:'Continuous batching'},{key:'mlock',label:'Lock model in memory'}, {key:'flash_attention',label:'Flash attention'},
    {key:'unified_kv_cache',label:'Unified KV cache'},{key:'offload_kv_cache',label:'Offload KV cache'},{key:'mmap',label:'Memory map'},
    {key:'keep_model_in_memory',label:'Keep model in memory'},{key:'fit',label:'Fit to available memory'}];
  constructor(readonly api:ApiService,private readonly settingsApi:SettingsService){}
  ngOnInit(){void this.initialize();}
  saveApiUrl(){if(!this.api.setBaseUrl(this.url)){this.urlError.set('Use http://127.0.0.1:<port> or http://localhost:<port> with a port from 1 to 65535.');return;}this.urlError.set('');void this.initialize();}
  async initialize(){this.loading.set(true);this.loadError.set('');try{await this.api.check();const response=await this.settingsApi.get();this.settings.set(response.data?.settings??null);if(!response.data?.settings)throw new Error('The settings endpoint returned no settings object.');}catch(e){this.loadError.set(message(e));}finally{this.loading.set(false);}}
  updateBackend(value:string){this.edit(s=>s.runtime_defaults.backend_name=value||null);}
  updateRuntime(value:string){this.edit(s=>s.runtime_defaults.runtime_id=value||null);}
  updatePlacement(key:keyof RuntimePlacement,value:string){this.edit(s=>{(s.runtime_defaults.placement as Record<string,unknown>)[key]=key==='gpu_layers'||key==='main_gpu'?(value===''?undefined:Number(value)):(value||undefined);});}
  updateLoadNumber(key:typeof this.numberFields[number]['key'],value:string){this.edit(s=>{(s.runtime_defaults.load as Record<string,unknown>)[key]=value===''?undefined:Number(value);});}
  updateLoadBool(key:typeof this.boolFields[number]['key'],value:boolean){this.edit(s=>{s.runtime_defaults.load[key]=value;});}
  updateLoadString(key:'numa'|'kv_cache_type_k'|'kv_cache_type_v',value:string){this.edit(s=>{s.runtime_defaults.load[key]=value||undefined;});}
  updateBehavior(value:string){if(value==='model'||value==='global')this.edit(s=>s.default_profile_behavior=value);}
  updateKeepLoaded(value:boolean){this.edit(s=>s.keep_last_model_loaded=value);}
  private edit(change:(settings:GlobalSettings)=>void){const current=this.settings();if(!current)return;const next=structuredClone(current);change(next);this.settings.set(next);this.saved.set(false);}
  async saveSettings(){const current=this.settings();if(!current)return;this.saving.set(true);this.saveError.set('');this.saved.set(false);try{const {managed_models_dir,config_dir,data_dir,...editable}=current;const response=await this.settingsApi.patch(editable);if(response.data?.settings)this.settings.set(response.data.settings);this.saved.set(true);}catch(e){this.saveError.set(message(e));}finally{this.saving.set(false);}}
}
function message(e:unknown):string{return e instanceof Error?e.message:String(e);}
